import test from 'node:test';
import assert from 'node:assert/strict';
import { createWeatherServer, getGoogleForecast } from '../server/google-weather.mjs';
const origin='https://legedith.github.io';
const row=i=>({interval:{startTime:new Date(Date.parse('2026-09-05T00:00Z')+i*3600000).toISOString()},temperature:{degrees:25,unit:'CELSIUS'}});
const response=data=>({ok:true,status:200,json:async()=>data});
async function withServer(options,callback){const s=createWeatherServer(options);await new Promise(resolve=>s.listen(0,'127.0.0.1',resolve));try{await callback(`http://127.0.0.1:${s.address().port}`);}finally{s.closeAllConnections();await new Promise(resolve=>s.close(resolve));}}
test('proxy paginates Google and keeps request parameters consistent',async()=>{const calls=[];const data=await getGoogleForecast({lat:17.45,lon:78.3,hours:25,apiKey:'test-only',fetchImpl:async url=>{const u=new URL(url);calls.push(u);return response({forecastHours:calls.length===1?Array.from({length:24},(_,i)=>row(i)):[row(24)],timeZone:{id:'Asia/Kolkata'},...(calls.length===1?{nextPageToken:'second'}:{})});}});assert.equal(calls.length,2);assert.equal(calls[1].searchParams.get('pageToken'),'second');assert.equal(calls[1].searchParams.get('hours'),'25');assert.equal(calls[0].searchParams.get('unitsSystem'),'METRIC');assert.equal(data.forecastHours.length,25);});
test('proxy rejects repeated pagination tokens',async()=>{await assert.rejects(()=>getGoogleForecast({lat:17.45,lon:78.3,hours:100,apiKey:'test-only',fetchImpl:async()=>response({forecastHours:[row(0)],nextPageToken:'same'})}),/pagination/);});
test('origin is required and exact, and invalid coordinates do not hit Google',async()=>{let calls=0;await withServer({apiKey:'test-only',allowedOrigins:[origin],fetchImpl:async()=>{calls++;return response({});}},async base=>{for(const headers of [{},{Origin:'https://attacker.example'}])assert.equal((await fetch(base+'/forecast?lat=17&lon=78&hours=24',{headers})).status,403);assert.equal((await fetch(base+'/forecast?lat=0&lon=0&hours=24',{headers:{Origin:origin}})).status,400);assert.equal((await fetch(base+'/forecast?lat=17&lon=78&hours=361',{headers:{Origin:origin}})).status,400);assert.equal(calls,0);});});
test('proxy returns no-store, attribution data and exact CORS origin',async()=>{await withServer({apiKey:'test-only',allowedOrigins:[origin],fetchImpl:async()=>response({forecastHours:[row(0)],timeZone:{id:'Asia/Kolkata'}})},async base=>{const r=await fetch(base+'/forecast?lat=17&lon=78&hours=1',{headers:{Origin:origin}});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('access-control-allow-origin'),origin);assert.equal((await r.json()).forecastHours.length,1);});});
test('proxy does not leak keys or upstream errors',async()=>{await withServer({apiKey:'SECRET_SENTINEL',allowedOrigins:[origin],fetchImpl:async()=>{throw new Error('https://example.com/?key=SECRET_SENTINEL');}},async base=>{const r=await fetch(base+'/forecast?lat=17&lon=78&hours=1',{headers:{Origin:origin}});assert.equal(r.status,502);assert(!((await r.text()).includes('SECRET_SENTINEL')));});});
test('proxy enforces its per-minute request limit',async()=>{let calls=0;await withServer({apiKey:'test-only',allowedOrigins:[origin],maxRequestsPerMinute:1,fetchImpl:async()=>{calls++;return response({forecastHours:[row(0)]});}},async base=>{const url=base+'/forecast?lat=17&lon=78&hours=1';assert.equal((await fetch(url,{headers:{Origin:origin}})).status,200);assert.equal((await fetch(url,{headers:{Origin:origin}})).status,429);assert.equal(calls,1);});});
test('proxy rejects unsupported methods, duplicate arguments and arbitrary upstream URLs',async()=>{await withServer({apiKey:'test-only',allowedOrigins:[origin]},async base=>{assert.equal((await fetch(base+'/forecast?lat=17&lat=18&lon=78&hours=1',{headers:{Origin:origin}})).status,400);assert.equal((await fetch(base+'/forecast?lat=17&lon=78&hours=1&url=https://evil.example',{headers:{Origin:origin}})).status,400);assert.equal((await fetch(base+'/forecast',{method:'POST',headers:{Origin:origin}})).status,405);});});
test('proxy has safe health and unconfigured responses',async()=>{await withServer({allowedOrigins:[origin]},async base=>{assert.equal((await fetch(base+'/healthz')).status,200);assert.equal((await fetch(base+'/forecast?lat=17&lon=78&hours=1',{headers:{Origin:origin}})).status,503);});});
test('per-day upstream budget is bounded independently of frontend requests',async()=>{let calls=0;await withServer({apiKey:'test-only',allowedOrigins:[origin],maxUpstreamPerDay:1,fetchImpl:async()=>{calls++;return response({forecastHours:[row(0)]});}},async base=>{const url=base+'/forecast?lat=17&lon=78&hours=1';await fetch(url,{headers:{Origin:origin}});assert.equal((await fetch(url,{headers:{Origin:origin}})).status,502);assert.equal(calls,1);});});
